### ISSUE TITLE
点立即启动会报错。

### ISSUE THREAD

**Issue by BestQu** [yejq/quartz-spring-manager#1]
org.quartz.JobPersistenceException: The job (xxx.xxx) referenced by the trigger does not exist.
at org.quartz.simpl.RAMJobStore.storeTrigger(RAMJobStore.java:321)
    at org.quartz.core.QuartzScheduler.triggerJob(QuartzScheduler.java:1064)
    at org.quartz.impl.StdScheduler.triggerJob(StdScheduler.java:326)
    at org.quartz.impl.StdScheduler.triggerJob(StdScheduler.java:314)

就是这一行：
  scheduler.triggerJob(name, group);

**Comment by BestQu** [comment]
我看了下源码，triggerJob参数是jobName和groupName 
`public void triggerJob(String jobName, String groupName) throws SchedulerException {
        this.triggerJob(jobName, groupName, (JobDataMap)null);
    }`
这里改一下就OK 了
`<button type="button" class="btn btn-warning btn-xs" onclick="triggerOperate('trigger', 'name=${triggerModel.trigger.jobName}&group=${triggerModel.trigger.jobGroup}')">立即启动</button>`
